export const SIGNIN_WITH_GOOGLE = "SIGNIN_WITH_GOOGLE";
export const SIGNOUT_FROM_GOOGLE = "SIGNOUT_FROM_GOOGLE";
export const LOGIN_WITH_FACEBOOK = "LOGIN_WITH_FACEBOOK";
export const LOGOUT_FROM_FACEBOOK = "LOGOUT_FROM_FACEBOOK";

export const CREATE_PLACE = "CREATE_PLACE";
export const FETCH_PLACES = "FETCH_PLACES";
export const FETCH_PLACE = "FETCH_PLACE";
export const EDIT_PLACE = "EDIT_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";
